# Generated by Django 5.0.2 on 2024-04-26 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveruser',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='driverDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenshipnumber', models.CharField(max_length=50)),
                ('licensenumber', models.CharField(max_length=50)),
                ('vehicleNumber', models.CharField(max_length=50)),
                ('license_front', models.ImageField(upload_to='documents/licensefront/')),
                ('license_back', models.ImageField(upload_to='documents/licenseback/')),
                ('citizenshipnumber_front', models.ImageField(upload_to='documents/citizenshipfront/')),
                ('citizenshipnumber_back', models.ImageField(upload_to='documents/citizenshipback/')),
                ('vehiclepage1', models.ImageField(upload_to='documents/vehiclepage1/')),
                ('vehiclepage2', models.ImageField(upload_to='documents/vehiclepage2/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.driveruser')),
            ],
        ),
    ]
