# Generated by Django 5.0.2 on 2024-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocuments',
            name='vechicleModel',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driveruser',
            name='isactive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
