# Generated by Django 5.0.2 on 2024-05-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_driverdocuments_vechiclemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdocuments',
            old_name='vechicleModel',
            new_name='vehicleModel',
        ),
    ]
