# Generated by Django 5.0.2 on 2024-04-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0002_acceptedride_canceledride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canceledride',
            old_name='canceledreason',
            new_name='canceledreaseon',
        ),
        migrations.RemoveField(
            model_name='acceptedride',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='acceptedride',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='acceptedride',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='acceptedride',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='acceptedride',
            name='user',
        ),
        migrations.RemoveField(
            model_name='canceledride',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='canceledride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='canceledride',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='canceledride',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='canceledride',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='canceledride',
            name='user',
        ),
        migrations.AddField(
            model_name='acceptedride',
            name='ride',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookride.riderequested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptedride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='canceledride',
            name='ride',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookride.riderequested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderequested',
            name='status',
            field=models.CharField(default='requested', max_length=50),
        ),
    ]
