# Generated by Django 5.0.2 on 2024-05-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0004_prebooking_cancelledprebooking_acceptedprebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledprebooking',
            name='prebooking',
        ),
        migrations.RemoveField(
            model_name='prebooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Acceptedprebooking',
        ),
        migrations.DeleteModel(
            name='Cancelledprebooking',
        ),
        migrations.DeleteModel(
            name='Prebooking',
        ),
    ]
