# Generated by Django 5.0.2 on 2024-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0007_acceptedprebooking_prebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebooking',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('completed', 'completed'), ('accepted', 'accepted'), ('requested', 'requested')], default='requested', max_length=50),
        ),
        migrations.AlterField(
            model_name='riderequested',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('completed', 'completed'), ('accepted', 'accepted'), ('requested', 'requested')], default='requested', max_length=50),
        ),
    ]
