# Generated by Django 5.0.2 on 2024-05-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0008_alter_prebooking_status_alter_riderequested_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebooking',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('requested', 'requested'), ('accepted', 'accepted'), ('completed', 'completed')], default='requested', max_length=50),
        ),
        migrations.AlterField(
            model_name='riderequested',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('requested', 'requested'), ('accepted', 'accepted'), ('completed', 'completed')], default='requested', max_length=50),
        ),
    ]
